.travis.yml
Gemfile
lib/dry/view/layout.rb
spec/integration/view_spec.rb
spec/spec_helper.rb

Instead of using a struct with a `page` accessor as the layout's scope, use a Rodakase::View::Part` object like we already do for the non-layout templates.
This allows rendering of partials via `== partial_name` instead of having to chain them onto the page object (i.e. `== page.partial_name`).
The general upshot is that it makes authoring layouts much more consistent with authoring templates by making the same partial rendering behaviour apply everywhere.
<hr>
_Copied from https://github.com/dry-rb/dry-web/pull/19, which was pushed back when dry-view was still a part of Rodakase/dry-web_

Use a part object as the layout template's scope

---

lib/dry/view/layout.rb

This is a slight procedural change that will allow things like sharing content from the template up to the layout. For example if a "content_for"-style method was made available to both the template and the layouts, then it would be important to render the template first so that it could provide the "content_for" data, which would then be used by the layout (e.g. useful for specifying page-specific content that needs to go into the layout’s `<head>`).
<hr>
_Copied from https://github.com/dry-rb/dry-web/pull/18, which was made back when dry-view was part of rodakase._

Render template content before rendering layout content

---

lib/dry/view/renderer.rb

Template file is not valid US-ASCII (Encoding::InvalidByteSequenceError) occurred when I try render layout with utf-8 characters on remote server.
Related to: https://github.com/hanami/view/issues/76

Fix error: Template file is not valid US-ASCII

---

lib/dry/view/layout.rb
lib/dry/view/path.rb
lib/dry/view/renderer.rb
spec/fixtures/templates_override/users.html.slim
spec/integration/view_spec.rb
spec/unit/layout_spec.rb
spec/unit/renderer_spec.rb

Replace `Dry::View::Layout`'s `root` config with `paths`, which accepts one or more directory paths. Templates will be searched on all of these paths, with the first match being used.
This will make it possible to ship view-oriented gems with bundled templates, as well as some potential for apps to share templates in interesting ways.
Obviously, the more template paths, the more file system checks we have to make in order to locate a template. At some point it'd probably be prudent to add caching of these, but for now, this change will make it possible for us to start shipping some of these view-oriented gems I hinted at above (like one to make pagination easy to handle across apps).
@solnic, what do you reckon?

Support multiple template paths

---

lib/dry/view/null_part.rb
lib/dry/view/part.rb
lib/dry/view/value_part.rb
spec/fixtures/templates/parts_with_args.html.slim
spec/fixtures/templates/parts_with_args/_box.html.slim
spec/integration/view_spec.rb
spec/unit/null_part_spec.rb
spec/unit/part_spec.rb
spec/unit/value_part_spec.rb

In a lot of the apps we work on, we've encountered a requirement to pass some data from _within a template_ to another partial. An example would be partials that require extra data or config related to how they should present themselves in a certain context, e.g. `== user.metadata_box(header_label: "Cool stats")`.
This change makes that possible. Since the arguments to the template call is still effectively _data_, this holds true to the dry-view philosophy of data-orientation.
I've still to improve the test coverage a little more, but I thought I'd throw it up now for anyone to comment on.
Code-wise, just one thing stands out: the inheritance of `Part` is getting a bit awkward, especially since we now need to transform `Part` and `NullPart` instances into `ValuePart` when they're called …

Make arguments to partial method calls available within their templates

---

.travis.yml
Gemfile
lib/dry/view.rb
lib/dry/view/controller.rb
spec/integration/view_spec.rb
spec/spec_helper.rb
spec/unit/controller_spec.rb

This is the first step in reorienting people’s approach to dry-view. Since the main job of `Dry::View::Layout` subclasses is to assemble dependencies, accept and process input, then prepare a list of locals for a view, the “controller” name is a better reflection of its actual work. This should also hopefully make people feel more comfortable with the idea that it's OK to inject a bunch of dependencies here, even though the end-result is "view"-related. In this new arrangement, the "view" is just the template, all of the Ruby stuff is part of a "view controller".

Rename layout to controller

---

lib/dry/view/renderer.rb

Before
```
Dry::View::Renderer::TemplateNotFoundError
Template login_forms could not be found in paths: - #<Dry::View::Path:0x007fb176abb5b0>
```
After
```
Dry::View::Renderer::TemplateNotFoundError
Template "login_forms" could not be found in paths: - /Users/kwando/projects/rpc_web/templates
```

Make message for TemplateNotFoundError more readable

---

lib/dry/view/null_part.rb
lib/dry/view/part.rb
lib/dry/view/value_part.rb
spec/fixtures/templates/parts_with_args/_box.html.slim
spec/spec_helper.rb
spec/unit/null_part_spec.rb
spec/unit/part_spec.rb
spec/unit/value_part_spec.rb

Use `Part.build` for any additional scope args passed when rendering partials. Do some refactoring to unify the handling of these extra args as well.

Unify handling of additional partial args and run through Part.build

---

lib/dry/view/controller.rb
spec/fixtures/templates/layouts/app.html.slim
spec/fixtures/templates/layouts/app.txt.erb
spec/integration/exposures_spec.rb
spec/integration/view_spec.rb
spec/unit/controller_spec.rb

Two renames here:
1. Rename the "scope" view controller option to "layout_scope", since it only applies to the layout
2. Rename the view part through which this scope is passed to the layout from "page" to "layout"
Both of these should hopefully increase clarity. In the case of (1), the option's intended use is clearer, and in the case of (2) , we don't use the notion of a "page" anywhere in dry-view, so simply calling the view part "layout" makes more sense, and it works pretty well from inside the template code, since "layout" seems more fitting inside an actual layout template.
Resolves #8

Rename layout parts and scope options

---

lib/dry/view/controller.rb
lib/dry/view/scope.rb
spec/fixtures/templates/layouts/app.html.slim
spec/fixtures/templates/layouts/app.txt.erb
spec/fixtures/templates/users.html.slim
spec/integration/exposures_spec.rb
spec/integration/view_spec.rb
spec/spec_helper.rb
spec/unit/controller_spec.rb
spec/unit/scope_spec.rb

This removes the `layout_scope` and replaces it with a `context`. The context is an object that is available in the scope for _all templates_ (layouts, templates and partials), and is looked up after any data otherwise available on that scope.
This makes it possible to set up a context object with common things that you need across all parts of your app's templates, like CSRF tags, asset URL generators, the current_user, etc.

Make a shared context available across layouts, templates and partials

---

lib/dry/view/scope.rb
spec/unit/scope_spec.rb

This reduces the risk of partials with names conflicting with data causing problems.

Resolve methods from scope in order of data, context, partials

---

.travis.yml
lib/dry/view/controller.rb

This allows us to remove some of the “special” options (`format`, `context`, and `locals`) before they get passed to the exposures to build up the final locals hash to pass to the scope.

Use keyword args for accepting input

---

lib/dry/view/controller.rb
lib/dry/view/exposure.rb
spec/integration/exposures_spec.rb
spec/unit/exposure_spec.rb

This is important for accessing instance data in cases where there are dependencies injected into the view controller, e.g.
```ruby
class MyView < Dry::View::Controller
include MyApp::Import[repo: "repositories.users"]
expose :users do
repo.listing
end
end
```

Make the view controller instance available to exposure blocks

---

lib/dry/view/decorator.rb
spec/fixtures/templates/decorated_parts.html.slim
spec/integration/decorator_spec.rb

Our standard decorator handles arrays of objects in a special way, decorating each member of the array as well as the array itself. Given we support specifying an `as:` option on exposures to provide a custom part class, we should also support providing a custom part class for array members. This PR implements this using the `each_as:` option.
This feels like the last thing we need before we can release the decorator and parts feature.

Support :each_as option for specifying part class for array members

---

lib/dry/view/decorator.rb
spec/integration/decorator_spec.rb

In response to the comments on #36 (thanks @solnic!), the `:as` exposure option now takes 2 forms for decorating arrays:
- `expose :things, as: MyPart` – decorate each _member_ of the array with `MyPart`
- `expose :things, as: {MyArrayPart => MyPart}` – decorate the array itself with `MyArrayPart` and each member with `MyPart`
This means the default dry-view decorator can now do everything it needs with a single `:as` option on exposures, and we can remove the `:each_as` option I introduced in #36. A nicer API! Thanks all.
Last thing I want to do before we release all of this is add a few API docs as well as updating the dry-rb.org docs to reflect this new `:as` behaviour.

Replace :each_as exposure option with hash argument form for :as option

---

lib/dry/view/scope.rb
spec/unit/scope_spec.rb

This fixed #39 
Raises `PartialNotFoundError ` if lookup returns false

Display useful error message when partial is not found

---

lib/dry/view/controller.rb
lib/dry/view/decorator.rb
lib/dry/view/exposure.rb
lib/dry/view/exposures.rb
lib/dry/view/part.rb
lib/dry/view/scope.rb

Have a look 😄 
```ruby
require "benchmark/ips"
def foo(seq, kw)
end
def fast
kw = { a: 1, b: 2, c: 3 }
foo(1, kw)
end
def slow
kw = { a: 1, b: 2, c: 3 }
foo(1, **kw)
end
Benchmark.ips do |x|
x.report("fast code description") { fast }
x.report("slow code description") { slow }
x.compare!
end
__END__
Warming up --------------------------------------
fast code description
108.311k i/100ms
slow code description
50.038k i/100ms
Calculating -------------------------------------
fast code description
1.596M (± 3.7%) i/s -      8.015M in   5.028700s
slow code description
576.682k (± 3.4%) i/s -      2.902M in   5.038684s
Comparison:
fast code description:  1596244.7 i/s
slow code description:   576682.4 i/s - 2.77x  slower
```

Fix keywords usage

---

CONTRIBUTING.md

Just noticed that the links to the discussions page on CONTRIBUTING.md seem not be up to date.

Update discussion links

---

.travis.yml
dry-view.gemspec
lib/dry/view/exposure.rb
lib/dry/view/exposures.rb
spec/fixtures/templates/edit.html.slim
spec/fixtures/templates/greeting.html.slim
spec/integration/exposures_spec.rb
spec/unit/exposure_spec.rb
spec/unit/exposures_spec.rb

Solve #44 
@timriley with this really small change we are able to support passing `keyword` arguments to the exposure block. Also we get `default` 🎉

Allow keyword arguments to be passed in exposure block arguments

---

lib/dry/view/default_renderer.rb
lib/dry/view/missing_renderer.rb
lib/dry/view/part.rb
spec/unit/part_spec.rb

This PR aims to address #43 by making the `renderer:` keyword argument optional when initialising a `View::Part`. 
In addition, a default renderer is provided that raises an exception whenever a method is called on it as a reminder to provide an actual renderer.

Allow for renderer to be optional and provide friendly default

---

lib/dry/view/exposure.rb
lib/dry/view/exposures.rb
spec/integration/exposures_spec.rb
spec/unit/exposure_spec.rb
spec/unit/exposures_spec.rb

This will allow setting a default value for exposure.
The change is motivated because on a `dry-web-roda` project I'm working I have to pass errors to a form view to display them, but if I do not have errors I'm forced to pass them as an empty array from my routes.
```ruby
r.get 'new' do
r.view 'tils.new', errors: []
end
```
So having the ability to set default values in our `views` objects make it simplier.
```ruby
module Tils
class New < TilWeb::View::Controller
configure do |config|
config.template = "tils/new"
end
expose :errors, default: []
end
end
```
What do you think @timriley

Allow setting default values for exposure

---

lib/dry/view/controller.rb
lib/dry/view/part.rb
lib/dry/view/renderer.rb
lib/dry/view/scope.rb
spec/fixtures/templates/_hello.html.slim
spec/unit/controller_spec.rb
spec/unit/part_spec.rb
spec/unit/renderer_spec.rb
spec/unit/scope_spec.rb

Do this by adding a `Renderer#partial` method and centralizing the logic around handling partials into Renderer. This means partial handling is no longer spread around `Part` and `Scope`.
At the same time, allow partials nested within subdirectories by translating partials named `"foo/bar"` into `"foo/_bar"` before doing the template lookup and rendering. This makes it easier for 3rd party gems shipping their own dry-view partials to prevent naming collisions with partials shipped as part of an app. n.b. partial files are still found using the same lookup path, this just allows some nesting within each of those directories.
I need this latter change particularly because I'm building up [icy-form](https://github.com/icelab/icy-form), which will ship with its own dry-view partials. Having …

Make partial rendering a dedicated role of the renderer

---

lib/dry/view/decorator.rb
lib/dry/view/part.rb
spec/integration/part/decorated_attributes_spec.rb
spec/unit/part_spec.rb

Resolves #45, closes #51
This PR implements decorated part attributes, following the "decoration from the inside" approach that I described in @GustavoCaso's attempt a  https://github.com/dry-rb/dry-view/pull/51#issuecomment-347048807.
Overview of the approach:
1. Part classes declare via `.decorate` which of their value's attributes they'd like decorated by part classes. The intended final API would be something like this:
```ruby
class ArticlePart < Dry::View::Part
decorate :author, as: AuthorPart
decorate :comments, as: CommentPart
decorate :author, :comments
end
```
2. Part classes expect a `decorator:` option to be provided to them when they're initialized
3. This decorator is called with each of the part's decorated attributes and it stores a hash of the results
4. When calling …

Parts with decorated attributes

---

lib/dry/view/part.rb
spec/integration/part/decorated_attributes_spec.rb

This keeps the decoration behaviour in view parts consistent with the behaviour at the view controller level (where only truthy values are decorated). This allows `if my_part.some_attribute` checks inside template to work as expected.
Fixes #59

Decorate truthy part attributes only

---

lib/dry/view/controller.rb
lib/dry/view/exposures.rb
lib/dry/view/rendered.rb
spec/integration/decorator_spec.rb
spec/integration/exposures_spec.rb
spec/integration/view_spec.rb
spec/unit/controller_spec.rb
spec/unit/exposures_spec.rb
spec/unit/rendered_spec.rb

Here's what you can do now:
```ruby
vc = MyView.new
rendered = vc.(users: users)
rendered.to_s
rendered.locals.keys
rendered[:users]
```
These locals are now wrapped in view parts as early as possible, including when they're made available as exposure dependencies. This means it's possible to take advantage of view-specific logic while building up the full set of locals.
Providing exposures wrapped in view parts as part of Dry::View::Rendered also opens up interesting possibilities for accessing specific _aspects_ of a rendered view, not just the whole rendered template string.
Resolves #64, resolves #69

Add Dry::View::Rendered to carry template output and locals (wrapped in view parts)

---

lib/dry/view/controller.rb
lib/dry/view/exposure.rb
spec/integration/controller/locals_spec.rb
spec/unit/exposure_spec.rb

Leave exposure values undecorated when exposures specify `decorate: false`

---

lib/dry/view/controller.rb
lib/dry/view/exposure.rb
spec/fixtures/templates/layouts/app_with_users.html.slim
spec/integration/exposures_spec.rb

Fix https://github.com/dry-rb/dry-view/issues/84
@timriley I opened this PR so we can start a discussion of the best way to allow layout access exposures.
This implementation uses a new setting `exposure_in_layout`
Based on that setting it will pass the locals to the layout or not.
I think this is not a bad idea, but I guess it could get out of hand depending on the size of locals since it would be in both `layout_scope` and `template_scope` and maybe would affect the performance of the library
I thought of having an exposure option base implementation where the user, can decide with exposure will be available in the layout.
```ruby
vc = Class.new(Dry::View::Controller) do
configure do |config|
config.paths = SPEC_ROOT.join('fixtures/templates')
config.layout = 'app_with_users' …
```

Add option to make exposure available to layout

---

lib/dry/view/context.rb
lib/dry/view/controller.rb
spec/fixtures/integration/context/decorated_attributes.html.slim
spec/integration/context_spec.rb
spec/integration/exposures_spec.rb
spec/integration/view_spec.rb
spec/spec_helper.rb
spec/unit/context_spec.rb
spec/unit/controller_spec.rb

Having the context object provide a baseline rendering context across all templates is helpful, but until now the context object was never able to vend view parts. This I feel has been a real shortcoming, since view parts are where we can ideally put so much of our view logic.
This PR attempts to address this (and resolves #66).
Here's how a context object might look now.
```ruby
class MyContext < Dry::View::Context
attr_reader :assets
decorate :assets
def initialize(assets:, **options)
@assets = assets
super
end
end
```
It'd be neater still if you're auto-injecting:
```ruby
class MyContext < Dry::View::Context
include Import["assets"]
decorate :assets
end
```
So now, whenever `#assets` is accessed from the context (either in a template or from within a view part), it will be decorated in …

Add base Context class with support for decorated attributes

---

Gemfile
dry-view.gemspec
spec/fixtures/integration/template_engines/erb/method_with_yield.html.erb
spec/fixtures/integration/template_engines/erb/render_and_yield.html.erb
spec/fixtures/integration/template_engines/erb/shared/_wrapper.html.erb
spec/fixtures/integration/template_engines/haml/method_with_yield.html.haml
spec/fixtures/integration/template_engines/haml/render_and_yield.html.haml
spec/fixtures/integration/template_engines/haml/shared/_wrapper.html.haml
spec/fixtures/integration/template_engines/slim/method_with_yield.html.slim
spec/fixtures/integration/template_engines/slim/render_and_yield.html.slim
spec/fixtures/integration/template_engines/slim/shared/_wrapper.html.slim
spec/integration/template_engines/erubi_spec.rb
spec/integration/template_engines/haml_spec.rb
spec/integration/template_engines/slim_spec.rb
spec/spec_helper.rb
spec/unit/controller_spec.rb

This gives us a start at making sure our baseline features are all at least _possible_ to use from views rendered with the various popular template engines.

Add specs for using various features with different template engines

---

lib/dry/view/part_builder.rb
lib/dry/view/path.rb
lib/dry/view/renderer.rb
lib/dry/view/scope_builder.rb

This PR uses `Dry::Core::Cache` to cache a few lookups that could otherwise be costly:
- Templates within paths
- Part classes within namespaces
- Scope classes within namespaces
@GustavoCaso I hope you don't mind me going ahead with this, I wanted to play around with what we could cache. And I figured we should use our existing caching helper from dry-core.
Before this change, we were ~5.5x slower than ActionController.
```
Warming up --------------------------------------
action_controller     1.000  i/100ms
dry-view     1.000  i/100ms
Calculating -------------------------------------
action_controller      6.519  (± 0.0%) i/s -     33.000
dry-view      1.171  (± 0.0%) i/s -      6.000
Comparison:
action_controller:        6.5 i/s
dry-view:        1.2 i/s - 5.56x slower
```
After this …

Cache various lookups with Dry::Core::Cache

---

lib/dry/view/part.rb
spec/unit/part_spec.rb

The output of Rendering#inspect may grow very large with both the context and inflector objects, so hide it from Part#inspect output, making parts easier to understand at a glance.
Resolves #70

Add custom Part#inspect including only name and value

---

spec/unit/renderer_spec.rb

References 889ac7b
This was a hairy bug, because it was responsible that utf8 partials (in nested folders) raised an error on rendering. I think it is good to have it covered to avoid regressions.

Test options are copied to new renderer with chdir

---

CHANGELOG.md
lib/dry/view/renderer.rb

This backports 889ac7b to 0.5.x branch, because it caused a regression where it was not possible to render utf8 partials. Do you think it is a good idea to release a new version with it?
References #104 
**Important**: I have never tried to backport anything in GH. I have just branched from `0.5.3`, cherry-picked the commit and added a commit with update version/changelog. If there is a better way, please go ahead.
Thanks :)

Backport chdir keeping options

---

benchmarks/benchmark_controller.rb
benchmarks/profile_controller.rb
spec/integration/context_spec.rb
spec/integration/controller/locals_spec.rb
spec/integration/exposures_spec.rb
spec/integration/part_builder_spec.rb
spec/integration/scope_spec.rb
spec/integration/template_engines/erbse_spec.rb
spec/integration/template_engines/erubi_spec.rb
spec/integration/template_engines/hamlit_spec.rb
spec/integration/template_engines/slim_spec.rb
spec/integration/view_spec.rb
spec/unit/controller_spec.rb

This:
- Reduces boilerplate in view controller classes,
- Makes it clearer how 3rd parties (e.g. hanami) can more easily apply their own default configuration values in view controller classes that they vend
Resolves #81

Update all specs to use blockless form of writing config values

---

lib/dry/view/context.rb
spec/unit/context_spec.rb

This ensures we don't end up prepending multiple modules when attributes are decorated across multiple calls
Resolves #100

Store all decorated attributes in a single prepended module

---

lib/dry/view/context.rb
lib/dry/view/decorated_attributes.rb
lib/dry/view/part.rb
spec/unit/context_spec.rb
spec/unit/decorated_attributes_spec.rb

Now attribute decoration on Context and Part behave identically, which means that it's now possible to decorate methods defined directly on Part classes, which wasn't possible with the previous behavior there (which relied on method_missing).
Resolves #99

Extract decorated attributes behavior into a single, shared module

---

lib/dry/view/rendering_missing.rb
lib/dry/view/scope.rb
spec/unit/scope_spec.rb

In this case a RenderingMissing is used. This may be useful for unit testing the aspects of a scope that don't rely on any rendering details.

Allow Scope objects to be initialized without a rendering

---

lib/dry/view/part.rb
lib/dry/view/rendering.rb
lib/dry/view/scope.rb
spec/unit/part_spec.rb
spec/unit/rendering_spec.rb
spec/unit/scope_spec.rb

Having access to the current format is useful in certain circumstances.
For example, from a Part which uses i18n to return translations that may need to differ per-format (e.g. translations for the HTML format may need embedded markup)
Resolves #111

Give access to current rendering format from Part and Scope

---

lib/dry/view.rb
spec/integration/view/exposures_spec.rb
spec/integration/view/locals_spec.rb

Since `context:` is a reserved keyword param for `View#call` anyway, and since exposure dependencies already implicitly have the context (since they're Part objects by that point), it should be no harm to make the context available for those who want to use it directly when building their exposures.
@waiting-for-dev What do you reckon? :)

Make context object available to exposures via matching keyword param

---

lib/dry/view.rb
spec/fixtures/integration/testing/view.html.slim
spec/fixtures/integration/testing/view/_feature_box.html.slim
spec/integration/testing/testing_parts_spec.rb

Add integration spec demonstrating unit testing of parts
Add a `View.template_rendering` method so that an appropriate rendering object for a particular view can be accessed (for testing purposes)
Resolves #68

Demonstrate unit testing parts; add small testing helpers

---

docsite/source/context.html.md

Fixes a typo in code sample in contexts documentation.

Fix typo in contexts documentation

---

lib/dry/view/path.rb
spec/unit/path_spec.rb

Delegating #to_s to a Pathname instance won't cause the value to be a
String as expected.
Call #to_s on the Pathname to ensure we get a String back.
Closes #133

Path should cast Pathname to String

---

docsite/source/index.html.md

A call to `super` is now needed any time you add your own constructor in a `Dry::View` class. Without it, the example given won't work:
```
6] pry(main)> 
[7] pry(main)> class ArticleView < Dry::View
[7] pry(main)*   config.paths = [File.join(__dir__, "templates")]  
[7] pry(main)*   config.part_namespace = Parts  
[7] pry(main)*   config.layout = "application"  
[7] pry(main)*   config.template = "articles/show"  
[7] pry(main)*   
[7] pry(main)*   attr_reader :article_repo  
[7] pry(main)*   
[7] pry(main)*   def initialize(article_repo:)  
[7] pry(main)*     @article_repo = article_repo    
[7] pry(main)*   end    
[7] pry(main)*   
[7] pry(main)*   expose :article do |slug:|  
[7] pry(main)*     article_repo.by_slug(slug)    
[7] pry(main)*   end    
[7] pry(main)* end  
=> …
```

Add super call to introduction example

---

lib/dry/view.rb
spec/integration/view_spec.rb

This PR addresses https://github.com/dry-rb/dry-view/issues/151
by using `default` and `constructor` keyword args during settings instantiation.

issue: fix dry-configurable warnings
